name: notes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_material_color_picker: ^1.2.0
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.2

  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/icon.png"
  android_12:
    color: "#ffffff"
    image: "assets/icons/android12_icon.png"
  android: true
  ios: true

flutter_launcher_icons:
  adaptive_icon_foreground: "assets/icons/android12_icon.png"
  adaptive_icon_background: "assets/icons/android12_icon.png"
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/android12_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton.ttf
    - family: Dancing
      fonts:
        - asset: assets/fonts/Dancing.ttf
    - family: Edu
      fonts:
        - asset: assets/fonts/Edu.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
flutter_intl:
  enabled: true
